import 'package:built_collection/built_collection.dart';
import 'package:mining_game/doodads/base/doodad_definition.dart';
import 'package:mining_game/doodads/base/doodad_id.dart';
import 'package:mining_game/doodads/doodad_types/house_doodad.dart';
import 'package:mining_game/item_management/item_definition.dart';
import 'package:mining_game/item_management/item_keys.dart';

final doodadDefinitionsExample = [
  const HouseDoodadDefinition(
      id: DoodadId.houseLevel1,
      name: 'Farmhouse',
      description: 'A shack with almost 4 walls',
      imageAsset: 'assets/images/all/house1.png',
      storeImageAsset: 'assets/images/all/house1.png',
      supportedLocations: {TileType.Grass},
      populationLimit: 10,
      peopleType: PersonType.peasant),
  RegenerativeHarvestableDoodadDefinition(
      id: DoodadId.rawFish,
      name: 'School of fish',
      description:
          'A group of playful fish that are so friendly. Why is your mouth watering? Do you not care at all about these beatiful creatures? o... You care about how they taste..',
      imageAsset: 'assets/images/all/fishing.png',
      storeImageAsset: 'assets/images/all/fishing.png',
      supportedLocations: {TileType.Water},
      ticksRequired: 4,
      ticksName: 'Populating',
      resourceRequiredToHarvestOne: 1,
      resourceMax: 4,
      resourceIncreasePerTick: 0.25,
      manualEffortToHarvest: 5,
      resourceGenerated: [ItemInstanceGenerator(Items.FOOD, 1)].build()),
  const AreaHarvestableDoodadDefinition(
      id: DoodadId.fisherman,
      name: 'Fisherman',
      description: '',
      imageAsset: 'assets/images/all/fishingHut.png',
      storeImageAsset: 'assets/images/all/fishingHut.png',
      supportedLocations: {TileType.Grass},
      ticksRequired: 10,
      ticksName: 'Fishing',
      range: 1),
  DiggerDoodadDefinition(
    id: DoodadId.ironDigger,
    name: 'Iron Digger',
    description:
        'Digs for resources and will store them in the planets resource depot.',
    imageAsset: 'assets/images/drills/5.png',
    storeImageAsset: 'assets/images/drills/5.png',
    supportedLocations: {TileType.IronDeposit},
    ticksRequired: 5,
    ticksName: 'Digging',
    itemMined: [ItemInstanceGenerator(Items.IRON_ORE, 1)].build(),
  ),
  RegenerativeHarvestableDoodadDefinition(
      id: DoodadId.tree,
      name: 'Tree',
      description:
          'A tree that flows in the wind. Must be cleared before a building can be placed here.',
      imageAsset: 'assets/images/tree.png',
      storeImageAsset: 'assets/images/tiles/03Trees/jungle_heavy.png',
      supportedLocations: {TileType.Grass},
      ticksRequired: 5,
      ticksName: 'Chopping',
      resourceRequiredToHarvestOne: 0.25,
      resourceMax: 1.0,
      resourceIncreasePerTick: 0.1,
      manualEffortToHarvest: 5,
      dynamicImageAssets: {
        100: 'assets/images/forestTest/forest100.png',
        90: 'assets/images/forestTest/forest90.png',
        75: 'assets/images/forestTest/forest75.png',
        65: 'assets/images/forestTest/forest65.png',
        60: 'assets/images/forestTest/forest60.png',
        50: 'assets/images/forestTest/forest50.png',
        25: 'assets/images/forestTest/forest25.png',
        1: 'assets/images/forestTest/forest10.png',
        0: 'assets/images/forestTest/forest0.png',
      },
      resourceGenerated: [ItemInstanceGenerator(Items.WOOD, 1)].build()),
  const AreaHarvestableDoodadDefinition(
      id: DoodadId.treeCutterHut,
      name: 'Tree cutter hut',
      description: 'Cuts down trees within 1 range.',
      imageAsset: 'assets/images/doodad/lumberHut.png',
      storeImageAsset: 'assets/images/doodad/lumberHut.png',
      supportedLocations: {TileType.Grass},
      ticksRequired: 20,
      ticksName: 'Cutting',
      range: 1),
  MaterialProcessorDoodadDefinition(
      id: DoodadId.sawMill,
      name: 'Sawmill',
      description: 'Cuts wood into planks',
      imageAsset: 'assets/images/doodad/sawmill.png',
      storeImageAsset: 'assets/images/doodad/sawmill.png',
      supportedLocations: {TileType.Grass},
      ticksRequired: 15,
      ticksName: 'Cutting',
      consumedMaterials: ItemRequirement.single(Items.WOOD, 2),
      itemsProduced: Items.PLANK.generateItemInstance(1)),
  MaterialProcessorDoodadDefinition(
      id: DoodadId.ironSmelter,
      name: 'Iron smelter',
      description: 'Smelts iron ore into iron bars.',
      imageAsset: 'assets/images/tiles/13-Icons/smithy.png',
      storeImageAsset: 'assets/images/tiles/13-Icons/smithy.png',
      supportedLocations: {TileType.Grass},
      ticksRequired: 15,
      ticksName: 'Smelting',
      consumedMaterials: ItemRequirement.single(Items.IRON_ORE, 2),
      itemsProduced: Items.IRON_BAR.generateItemInstance(1)),
].build();
