import 'package:mining_game/item_management/item_definition.dart';
import 'package:mining_game/item_management/item_keys.dart';

final itemModels = [
  const ItemDefinition.resourceDefinition(
      id: Items.ROCK,
      name: 'Black Rock',
      namePlural: 'Black rocks',
      description: 'Often found in dark caves',
      image: 'assets/images/placeholder.png',
      maxStackSize: 100),
  const ItemDefinition.resourceDefinition(
      id: Items.FOOD,
      name: 'Food',
      namePlural: 'Food',
      description: 'Test food object',
      image: 'assets/images/all/foodTest1.png',
      maxStackSize: 1000),
  const ItemDefinition.swordDefinition(
      id: Items.SWORD,
      name: 'Sword',
      namePlural: 'Swords',
      description: 'Point stick',
      image: 'assets/images/placeholder.png',
      attributes: {WeaponAttributes.SHARP: 10.0}),
  const ItemDefinition.resourceDefinition(
      id: Items.IRON_ORE,
      name: 'Iron ore',
      namePlural: 'Iron ore',
      description: 'Can be mined',
      image: 'assets/images/all/ironOre.png',
      maxStackSize: 100),
  const ItemDefinition.resourceDefinition(
      id: Items.IRON_BAR,
      name: 'Iron bar',
      namePlural: 'Iron bars',
      description: 'A smelted form of iron ready to be used for crafting.',
      image: 'assets/images/minerals/iron.png',
      maxStackSize: 100),
  const ItemDefinition.resourceDefinition(
      id: Items.COPPER,
      name: 'Copper',
      namePlural: 'Copper',
      description: 'Can be mined',
      image: 'assets/images/minerals/copper.png',
      maxStackSize: 100),
  const ItemDefinition.resourceDefinition(
      id: Items.SHARP_ROCK,
      name: 'Sharp rock',
      namePlural: 'Sharp rocks',
      description: 'A useless rock',
      image: 'assets/images/minerals/copper.png',
      maxStackSize: 100),
  const ItemDefinition.resourceDefinition(
      id: Items.SMALL_ROCK,
      name: 'Small rock',
      namePlural: 'Small rocks',
      description: 'A useless rock',
      image: 'assets/images/minerals/copper.png',
      maxStackSize: 100),
  const ItemDefinition.drillDefinition(
      id: Items.TEST_DRILL,
      name: 'Test drill',
      description: 'I do extra damage',
      image: 'assets/images/placeholder.png',
      damage: 4),
  const ItemDefinition.resourceDefinition(
      id: Items.CREDIT,
      name: 'Credit',
      namePlural: 'Credits',
      description: 'A form of currency.',
      image: 'assets/images/money.png',
      maxStackSize: 100),
  const ItemDefinition.resourceDefinition(
      id: Items.WOOD,
      name: 'Wood',
      description: 'Unprocessed wood',
      image: 'assets/images/1Icons/wood.png',
      maxStackSize: 100),
  const ItemDefinition.resourceDefinition(
      id: Items.PLANK,
      name: 'Plank',
      description: 'Processed wood',
      image: 'assets/images/1Icons/plank.png',
      maxStackSize: 100),
  const ItemDefinition.minerDefinition(
      id: Items.MINER1,
      name: 'Junk miner',
      description:
          'Salvaged from a garage sale. Barely functional and guzzles gas',
      radius: 1,
      depth: 1,
      baseDamage: 1,
      baseHopperSize: 50,
      fuelConsumption: 5,
      image: 'assets/images/drills/1.jpg'),
  const ItemDefinition.minerDefinition(
      id: Items.MINER2,
      name: 'Basic miner',
      description: 'Generic off the shelf miner',
      radius: 1,
      depth: 1,
      baseDamage: 2,
      baseHopperSize: 150,
      fuelConsumption: 5,
      image: 'assets/images/drills/2.jpg'),
  const ItemDefinition.minerDefinition(
      id: Items.MINER3,
      name: 'Test miner 3',
      description: 'This is the third miner',
      radius: 1,
      depth: 1,
      baseDamage: 1,
      baseHopperSize: 50,
      fuelConsumption: 5,
      image: 'assets/images/drills/3.png'),
  const ItemDefinition.minerDefinition(
      id: Items.MINER4,
      name: 'Test miner 4',
      description: 'This is the fourth miner',
      radius: 1,
      depth: 1,
      baseDamage: 1,
      baseHopperSize: 50,
      fuelConsumption: 5,
      image: 'assets/images/drills/4.jpg'),
  const ItemDefinition.minerDefinition(
      id: Items.MINER5,
      name: 'Test miner 5',
      description: 'This is the 5th miner',
      radius: 1,
      depth: 1,
      baseDamage: 1,
      baseHopperSize: 50,
      fuelConsumption: 5,
      image: 'assets/images/drills/5.png'),
];
